//
//  AreaSelectPresenter.swift
//  TourDemo_CleanSwift
//
//  Created by N4158 on 2022/02/16.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AreaSelectPresentationLogic
{
  func presentFetchAreaItems(response: AreaSelect.FetchAreaItems.Response)
}

class AreaSelectPresenter: AreaSelectPresentationLogic
{
  weak var viewController: AreaSelectDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchAreaItems(response: AreaSelect.FetchAreaItems.Response)
  {
      let areas = response.areaItem.response.body.items.item
      var displayModels:[AreaSelect.FetchAreaItems.ViewModel.DisplayedAreaItem] = []
      
      for area in areas {
          let displayModel = AreaSelect.FetchAreaItems.ViewModel.DisplayedAreaItem(title: area.name, code: area.code)
          displayModels.append(displayModel)
      }
      
    let viewModel = AreaSelect.FetchAreaItems.ViewModel(displayedAreaItems: displayModels)
    viewController?.displayAreaItems(viewModel: viewModel)
  }
}
