//
//  AreaSelectModels.swift
//  TourDemo_CleanSwift
//
//  Created by N4158 on 2022/02/16.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AreaSelect
{
  // MARK: Use cases
  
  enum FetchAreaItems
  {
    struct Request
    {
        var areaCode:String
    }
    struct Response
    {
        var areaItem:AreaModel
    }
    struct ViewModel
    {
        struct DisplayedAreaItem
        {
            var title:String
            var code:Int
        }
        
        var displayedAreaItems:[DisplayedAreaItem]
    }
  }
}
