//
//  FestivalDetailInteractor.swift
//  TourDemo_CleanSwift
//
//  Created by N4158 on 2022/02/08.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FestivalDetailBusinessLogic
{
  func getFestivalInfo()
}

protocol FestivalDetailDataStore
{
    var festivalInfo:Festival! { get set }
}

class FestivalDetailInteractor: FestivalDetailBusinessLogic, FestivalDetailDataStore
{
  var presenter: FestivalDetailPresentationLogic?
  var worker: FestivalDetailWorker?
  var festivalInfo: Festival!
  
  // MARK: Do something
  
    func getFestivalInfo()
    {
        guard let value = self.festivalInfo else { return }
        
        let response = FestivalDetail.FetchItem.Response(item: value)
        presenter?.presentFestivalInfo(response: response)
    }
}
