//
//  FestivalDetailPresenter.swift
//  TourDemo_CleanSwift
//
//  Created by N4158 on 2022/02/08.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FestivalDetailPresentationLogic
{
    func presentFestivalInfo(response: FestivalDetail.FetchItem.Response)
}

class FestivalDetailPresenter: FestivalDetailPresentationLogic
{
     var viewController: FestivalDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentFestivalInfo(response: FestivalDetail.FetchItem.Response)
    {
        let displayedModel = FestivalDetail.FetchItem.ViewModel.DisplayedFestivalItem(firstImage:response.item.firstimage, title: response.item.title, addr: response.item.addr1, tel: response.item.tel)
        viewController?.displayFestival(viewModel: displayedModel)
    }
}
