//
//  FestivalDetailWorker.swift
//  TourDemo_CleanSwift
//
//  Created by N4158 on 2022/02/08.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FestivalDetailWorker
{
  func doSomeWork()
  {
  }
}
