//
//  SearchMapInteractor.swift
//  TourDemo_CleanSwift
//
//  Created by N4158 on 2022/02/07.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol SearchMapBusinessLogic
{
  func doSomething(request: SearchMap.FetchLocationItems.Request)
}

protocol SearchMapDataStore
{
    var searchItem:LocationModel? { get }
}

class SearchMapInteractor: SearchMapBusinessLogic, SearchMapDataStore
{
    var searchItem: LocationModel?
    let disposeBag = DisposeBag()
    var presenter: SearchMapPresentationLogic?
    var worker: SearchMapWorker?
  
  // MARK: Do something
  
  func doSomething(request: SearchMap.FetchLocationItems.Request)
  {
      if worker == nil {
          worker = SearchMapWorker()
      }
      
      worker?.doSearchWork(request: request).subscribe { model in
          self.searchItem = model
          let response = SearchMap.FetchLocationItems.Response(searchItem: model)
          self.presenter?.presentFetchSearchItems(response: response)
      } onError: { error in
          print(error.localizedDescription)
      }.disposed(by: disposeBag)
  }
}
