//
//  SearchFestivalRouter.swift
//  TourDemo_CleanSwift
//
//  Created by N4158 on 2022/02/07.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchFestivalRoutingLogic
{
    func routeToAreaSelect(segue: UIStoryboardSegue?)
    func routeToFestivalDetail(segue: UIStoryboardSegue?)
}

protocol SearchFestivalDataPassing
{
    var dataStore: SearchFestivalDataStore? { get }
}

class SearchFestivalRouter: NSObject, SearchFestivalRoutingLogic, SearchFestivalDataPassing
{
    weak var viewController: SearchFestivalViewController?
    var dataStore: SearchFestivalDataStore?
    
    // MARK: Routing
    
    func routeToAreaSelect(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! AreaSelectViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToAreaSelect(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "AreaSelectViewController") as! AreaSelectViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToAreaSelect(source: dataStore!, destination: &destinationDS)
            navigateToAreaSelect(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToFestivalDetail(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! FestivalDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToFestivalDetail(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "AreaSelectViewController") as! FestivalDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToFestivalDetail(source: dataStore!, destination: &destinationDS)
            navigateToFestivalDetail(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToAreaSelect(source: SearchFestivalViewController, destination: AreaSelectViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToFestivalDetail(source: SearchFestivalViewController, destination: FestivalDetailViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToAreaSelect(source: SearchFestivalDataStore, destination: inout AreaSelectDataStore)
    {
        destination.areaCodeSubject = source.areaCodeSubject
    }
    
    func passDataToFestivalDetail(source: SearchFestivalDataStore, destination: inout FestivalDetailDataStore)
    {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        destination.festivalInfo = source.searchItem?.response.body.items.item[selectedRow!]
    }
}
