//
//  SearchKeywordInteractor.swift
//  TourDemo_CleanSwift
//
//  Created by N4158 on 2022/02/07.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol SearchKeywordBusinessLogic
{
    func doSearch(request: SearchKeyword.FetchKeywordItems.Request)
}

protocol SearchKeywordDataStore
{
  //var name: String { get set }
}

class SearchKeywordInteractor: SearchKeywordBusinessLogic, SearchKeywordDataStore
{
    let disposeBag = DisposeBag()
    var presenter: SearchKeywordPresentationLogic?
    var worker: SearchKeywordWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSearch(request: SearchKeyword.FetchKeywordItems.Request)
    {
        if worker == nil {
            worker = SearchKeywordWorker()
        }
        worker = SearchKeywordWorker()
        
        worker?.doSearchWork(request: request).subscribe { model in
            let response = SearchKeyword.FetchKeywordItems.Response(searchItem: model)
            self.presenter?.presentFetchSearchItems(response: response)
            
        } onError: { error in
            print(error.localizedDescription)
        }.disposed(by: disposeBag)
        
    }
}
