//
//  SearchKeywordPresenter.swift
//  TourDemo_CleanSwift
//
//  Created by N4158 on 2022/02/07.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchKeywordPresentationLogic
{
    func presentFetchSearchItems(response: SearchKeyword.FetchKeywordItems.Response)
}

class SearchKeywordPresenter: SearchKeywordPresentationLogic
{
    weak var viewController: SearchKeywordDisplayLogic?
    
    // MARK: Do something
    
    func presentFetchSearchItems(response: SearchKeyword.FetchKeywordItems.Response)
    {
        let keywords = response.searchItem.response.body.items.item
        var displayModels:[SearchKeyword.FetchKeywordItems.ViewModel.DisplayedSearchItem] = []
        
        //DisplayModel로 변경
        for festival in keywords {
            let displayModel = SearchKeyword.FetchKeywordItems.ViewModel.DisplayedSearchItem(title: festival.title, addr1: festival.addr1, addr2: festival.addr2, firstImage1: festival.firstimage, firstImage2: festival.firstimage2, tel: festival.tel, mapx: festival.mapx, mapy: festival.mapy)
            displayModels.append(displayModel)
        }
        
        let viewModel = SearchKeyword.FetchKeywordItems.ViewModel(displayedSearchItems: displayModels)
        viewController?.displaySearchItem(viewModel: viewModel)
    }
    
  }

